### ISSUE TITLE
MyST plugin

### ISSUE THREAD

**Issue by hukkinj1** [executablebooks/mdformat#172]
Build `mdformat-myst` plugin.

Come up with a set of parser and renderer extensions to be able to format MyST. Many of the syntax extensions make sense outside the MyST context, so they should be self-contained plugins that `mdformat-myst` requires and activates, similar to how `mdformat-gfm` does with `mdformat-tables`.

### Syntax extensions

- [x] Front matter ([mdformat-frontmatter](https://github.com/butler54/mdformat-frontmatter))
- [x] Tables ([mdformat-tables](https://github.com/executablebooks/mdformat-tables))
- [x] Directives (This works even with no changes implemented. The blocks will be parsed as if they were code blocks, which means that the block content will be left unchanged. This is fine. Special parsing/formatting logic can be added though if desired.)
- [x] Math (both block level and inline) (parser in [mdit-py-plugins/dollarmath](https://github.com/executablebooks/mdit-py-plugins/blob/master/mdit_py_plugins/dollarmath/index.py))
- [x] LineComment (parser in [mdit-py-plugins/myst-blocks](https://github.com/executablebooks/mdit-py-plugins/blob/master/mdit_py_plugins/myst_blocks/index.py))
- [x] BlockBreak (parser in [mdit-py-plugins/myst-blocks](https://github.com/executablebooks/mdit-py-plugins/blob/master/mdit_py_plugins/myst_blocks/index.py))
- [x] Footnote ([mdformat-footnote](https://github.com/gaige/mdformat-footnote/))
- [x] Role (parser in [mdit-py-plugins/myst-role](https://github.com/executablebooks/mdit-py-plugins/blob/master/mdit_py_plugins/myst_role/index.py))
- [x] Target (parser in [mdit-py-plugins/myst-blocks](https://github.com/executablebooks/mdit-py-plugins/blob/master/mdit_py_plugins/myst_blocks/index.py))

### TODO
- [x] Implement all extensions
- [ ] Wait for compatible mdformat-footnote release (https://github.com/hukkinj1/mdformat-myst/issues/2)
- [x] Release on PyPI
- [x] Mention the plugin in mdformat docs

### Links
- [This](https://github.com/executablebooks/MyST-Parser/blob/0d91280861173762b3e207ae8a23d0b873c29dd6/myst_parser/main.py#L152) seems to be the place where myst-parser itself prepares a `MarkdownIt` instance for myst parsing. We should set the same extensions in `myst_plugin.update_mdit()`. Also see [this place](https://github.com/executablebooks/MyST-Parser/blob/0d91280861173762b3e207ae8a23d0b873c29dd6/myst_parser/main.py#L194) where myst-parser sets MarkdownIt options.

**Comment by hukkinj1** [comment]
Started implementing in https://github.com/hukkinj1/mdformat-myst/

**Comment by hukkinj1** [comment]
@chrisjsewell do you know the story behind [these](https://github.com/executablebooks/MyST-Parser/blob/0d91280861173762b3e207ae8a23d0b873c29dd6/myst_parser/main.py#L158) `.disable("footnote_inline")` and `.disable("footnote_tail")`? Is special handling something an mdformat plugin would need to replicate?

**Comment by chrisjsewell** [comment]
Well `footnote_inline` does not have a built-in equivalent in the sphinx AST and `footnote_tail` is just a "post-processing" step that moves all the footnote tokens to the end of the stream, which is not necessary for myst-parser
