### ISSUE TITLE
mdformat escapes "todo-list" syntax

### ISSUE THREAD

**Issue by arwedus** [executablebooks/mdformat#300]
### Describe the problem

To-do lists are a popular extension of markdown, e.g. github and Bitbucket use them and VS Code markdown renderer supports them:

```md
Todo list:

- [ ] Create a plantuml diagram
- [x] Add input spec
```

Unfortunately, mdformat escapes those brackets:

```md
Todo list:

- \[ \] Create a plantuml diagram
- \[x\] Add input spec
```

Therefore please 

- [ ] let mdformat detect the todo-list item and keep it as-is.

### Steps to reproduce

1. copy the text above in a new markdown file
2. run mdformat on it.

### The version of Python you're using

3.8.9

### Your operating system

Ubuntu Linux 18.04 LTS

### Versions of your packages

mdformat 0.7.10 (mdformat_tables: 0.4.1, mdformat_frontmatter: 0.4.1, mdformat_myst: 0.1.4)

**Comment by chrisjsewell** [comment]
>  github and Bitbucket use them

Then you may want to parse Github Flavoured Markdown 😉  https://github.com/hukkin/mdformat-gfm

**Comment by hukkin** [comment]
Hi there!

Mdformat is, by default, CommonMark compatible and the syntax you mention is not part of CommonMark.

Please do
```console
pip install mdformat-gfm
```

**Comment by arwedus** [comment]
@hukkin: does CommonMark require you to escape each and every occurrence of a character that could be used as special character?

@chrisjsewell: I use mdformat-myst because this example is from a myst markdown file.
I have not yet checked if myst also understands it...

**Comment by hukkin** [comment]
> does CommonMark require you to escape each and every occurrence of a character that could be used as special character

No it _every_ occurence. But if you leave these always unescaped you end up having unintended links, references, etc.

> I use mdformat-myst because this example is from a myst markdown file.
I have not yet checked if myst also understands it...

You can do 
```console
pip install mdformat-myst mdformat-gfm
```

**Comment by chrisjsewell** [comment]
>  use mdformat-myst because this example is from a myst markdown file. I have not yet checked if myst also understands it...

MyST has extension syntaxes (https://myst-parser.readthedocs.io/en/latest/syntax/optional.html) of which task-lists are one.
I would eventually like to add enabling these in mdformat-myst as a CLI option.
Not done yet though 😅

**Comment by arwedus** [comment]
> 
> ```
> pip install mdformat-myst mdformat-gfm
> ```

And that works just fine. Thank you!
